version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees: ["glazelf"]
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    assignees: ["glazelf"]
    schedule:
      interval: "daily"
      time: "06:00"
