version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    assignees: ["glazelf"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    assignees: ["glazelf"]
    schedule:
      interval: "daily"
