
name: Prettier
on:
  workflow_dispatch:
  #Runs weekly ig
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: "master-branch"

jobs:
  format:
    if: github.repository == 'Glazelf/NinigiBot'
    runs-on: ubuntu-latest
    name: Format Files
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - name: Prettier
        run: npm run format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: format-files
        with:
          commit_message: "chore(styling): format files"
          skip_checkout: true
          branch: "formatting-${{ github.sha }}"
          create_branch: true

      # create PR using GitHub CLI if files were formatted
      - name: create PR with formatted files
        if: steps.format-files.outputs.changes_detected == 'true'
        id: create-pr
        run: git checkout formatting-${{ github.sha }} && gh pr create --base master --head formatting-${{ github.sha }} --title 'Merge formatting into master' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
